### ISSUE TITLE
www.qpm.io: broken download link

### ISSUE THREAD

**Issue by ElderOrb** [Cutehacks/qpm#3]
On attempt to download qpm via google chrome I'm getting qpm.xml file and "Failed - No file" message. Using download master I'm getting: 

14 9/10/2015 20:52:12 Header not recognized or 505 [1]

p.s. qpm looks like extremely promising project for me (well, the idea itself as I failed to get it working yet :) ). Looking forward to try it as soon as it get more stable.

**Comment by jrbarron** [comment]
@ElderOrb Thanks for the heads up! It looks like we forgot to append `.exe` to the filename of the download link. You are the first Windows tester :) We'll fix the website, shortly, but you can grab the binary directly from here:

https://storage.googleapis.com/www.qpm.io/download/latest/windows_386/qpm.exe

Note that the qpm.io registry is not really seeded with anything useful yet, but we plan on reaching out to some people this week. Also, I'm not sure the binary we have published on the website is the latest, but I'll try to fix that tonight since we have made some changes to the package format.

**Comment by mariusbu** [comment]
The link should be fixed now. Should be deployed soon.

**Comment by ElderOrb** [comment]
Thank you for the quick replay!

**Comment by ElderOrb** [comment]
Actually the link is still broken and looks like this: https://storage.googleapis.com/www.qpm.io/download/latest/windows_386/qpm

.. although appending with ".exe" fixes the issue

Oh, I beg pardon, for some reasons I've read 'should be deployed soon' as 'should be deployed now' :)

**Comment by jrbarron** [comment]
Just deployed everything so this should be fixed now.
