### ISSUE TITLE
QPM Windows: Error with qpm.json

### ISSUE THREAD

**Issue by Skycoder42** [Cutehacks/qpm#41]
Apparently, some packages fail to install on windows. Other platforms are fine.

See skycoder42/QtIFW-Advanced-Setup#1 as a concrete example. It tries to find the `qpm.json` inside of the translations subdirectory, which obviously fails, instead of using the `qpm.json` in the root directory.

**Comment by benlau** [comment]
I have tried to run `qpm install de.skycoder42.qtifw-advanced-setup" in AppVeyor and it works :o

Reference: 
https://ci.appveyor.com/project/benlau/qtshell/build/1.0.19

**Comment by Skycoder42** [comment]
Running it on an updated Window 10 VM fails (both, via cmd and powershell). I also tried your testable package, it's the same:

![image](https://cloud.githubusercontent.com/assets/9221346/26497347/789d2488-422b-11e7-909a-829893cc64f0.png)

**Edit:** I installed qpm by downloading the binary from the website, and not via go. This could be relevant for the issue

**Comment by Skycoder42** [comment]
It seems this does not just happen on this package, there are more! I'll update this list accordingly:
- de.skycoder42.kokke.tiny-aes128-c
- de.skycoder42.qrng
- de.skycoder42.qtifw-advanced-setup
- de.skycoder42.qhotkey

The only thing those packages share, is that they do have subdirectories

**Comment by Skycoder42** [comment]
I think this issue is rather urgent, since this makes qpm unusable on windows, if subdirectories are present.

@benlau Can we get the compiled qpm.exe of your appveyor build? It would be great to test if it only works on the system it was compiled on, or on all systems.

**Comment by benlau** [comment]
@Skycoder42 You may get the qpm.exe built by AppVeyor at:

https://ci.appveyor.com/project/benlau/junkcode/build/artifacts

It is proven to work with your package.

**Comment by jrbarron** [comment]
Sorry I haven't replied here earlier, but I think this issue has been reported earlier and is fixed by downloading the latest version of the binaries. For Windows, they are linked in this task: https://github.com/Cutehacks/qpm/issues/24 Let me know if this works and I can close the task.

**Comment by Skycoder42** [comment]
I can try out in 2 about days. 

But if you say it's already fixed, why are the official binaries at your **website** outdated? I checked the release page and the latest is 0.10.0 from 2015? Checking the commit history shows clearly that this one is not really up to date. Is there any reason you haven't published a newer version with those fixes yet? For me it's fine to download from some github issue, but the "normal user" will download the binaries from the website! (The same goes for the Arch package, too)

**Comment by Skycoder42** [comment]
it does indeed work with that one. The question, why such a critical error was not fixed as patch update (i.e. 0.10.1). I can recommend to use this version until 0.11.0 has been released, but I would be nice to see this as official release as quickly as possible.

**Comment by 0xlitf** [comment]
I build the qpm by myself, it works.
go get qpm.io/qpm
go build qpm.io/qpm

evn: go 1.8.1 Windows 10

**Comment by mariusbu** [comment]
Closing this issue, since it seems that this has been fixed in v0.11.0.
